#:schema https://json.schemastore.org/any.json

env_files = [".env"]
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  entrypoint = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/httpserver"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "yaml", "yml", "html"]
  include_file = ["config.yaml"]
  kill_delay = "10s"
  log = "tmp/build-errors.log"
  poll = false
  rerun = false
  send_interrupt = true
  stop_on_error = false

[color]
  app = "white"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
